### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TomPed**
We want a more standard style for the Codecov example `READMD.md`s. I've added and moved around a few things. @richelbilderbeek it looks like you've done some work on this. Would you mind reviewing the changes?

### CODE REVIEW

**Comment by stevepeak** [comment]
@richelbilderbeek If you don't mind checking these changes it would help us out a lot. Thank you!

**Review by richelbilderbeek — APPROVED** [review]
Being not a Codecov employer, this commit makes me wonder of the second C should also be in uppercase?

**Comment by richelbilderbeek** [comment]
Happy to help, looks great!

**Comment by thomasrockhu** [comment]
Closing in favor of https://github.com/codecov/example-cpp11/pull/2

**Pull request closed without merging**
